import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import classes from "../styles/Home.module.css";
import { useThemeBtn } from "../hooks/useThemeBtn";
import { useTheme } from "../hooks/useTheme";

const Home: NextPage = () => {
	const theme = useTheme();
	return (
		<div
			className={`${theme.dark ? classes.darkContainer : classes.container}`}>
			<Head>
				<title>Upodiy</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<h1 className={`${theme.dark ? classes.darkHeader : classes.header}`}>
				Swipe Right
			</h1>

			<div
				className={`${
					theme.dark ? classes.darkLinksContainer : classes.linksContainer
				}`}>
				<div className={`${theme.dark ? classes.darkLink : classes.link}`}>
					<Link href='/signup'>
						<a>Create Account</a>
					</Link>
				</div>
				<div className={`${theme.dark ? classes.darkLink : classes.link}`}>
					<Link href='/signin'>
						<a>Sign in</a>
					</Link>
				</div>
			</div>

			{useThemeBtn()}
		</div>
	);
};

export default Home;
